<?php
	$page = "brochure";
	$keywords = "property brochure";
	$description = "Urban Activation - Property Brochure";
	$title = "Urban Activation - Property Brochure";
	include("inc/head-brochure-template.php");
	$err = false;
	$errString = "<h2>Sorry, the property you are looking for does not exist. Please try another property search <a href='".$site_path."'>here</a>.</h2>";
	if(isset($_GET['url'])){
		$pID = getPropertyIDByURL($_GET['url']);
		if($pID>0){
			//property exist
			$property = array();$property_details = array();$property_mob_images=array();$property_images=array();
			$property = getPropertyDetails($pID);
			while($property_details_row = mysql_fetch_array($property,MYSQL_ASSOC)){
				$property_details['title'] = $property_details_row['title'];
				$property_details['cat'] = $property_details_row['category_id'];
				$property_details['propURL'] = $property_details_row['seo_page_name'];
				$property_details['address'] = $property_details_row['address'];
				$property_details['suburb'] = $property_details_row['suburb'];
				$property_details['state'] = $property_details_row['state'];
				$property_details['keyFeatures'] = $property_details_row['keyFeatures'];
				$property_details['inspections'] = $property_details_row['inspections'];
				if($property_details_row['nras']==1) $property_details['keyFeatures'] .= "<ul><li>NRAS approved property</li></ul>";
				$property_details['body'] = $property_details_row['body'];
				$property_details['displayPrice'] = $property_details_row['displayPrice'];				
				$property_details['rent'] = $property_details_row['rent'];
				$property_details['bedrooms'] = (int)$property_details_row['numBedrooms'];
				$property_details['bathrooms'] = (int)$property_details_row['numBathrooms'];
				$property_details['carparks'] = (int)$property_details_row['numParking'];
				
				$property_details['price'] = $property_details_row['price'];
				$property_details['priceRangeMax'] = $property_details_row['priceRangeMax'];
				$property_details['priceRangeMin'] = $property_details_row['priceRangeMin'];
				$property_details['googleMap'] = $property_details_row['googleMap'];
				$property_details['featureImage'] = getPropFeatureImageURL($property_details_row['id']);
				$property_images = getPropAllImagesURL($property_details_row['id'],0);
				$property_mob_images = getPropAllImagesURL($property_details_row['id'],1);
				/*$property_details['floorPlans'] = $property_details_row['floorPlans'];
				$property_details['brochure'] = $property_details_row['brochure'];
				$msgBoxContent = $property_details_row['title'].", ".$property_details_row['suburb']." ".$property_details_row['state'];	*/
			}
		} else {
			$err = true;	
		}				
	} else {
		//no property url given
		$err = true;
	}
?>	
    <div id="content" class="content-inside">
    	<div id="col-left">
        	<!--<h2>Property Brochure</h2>-->
        
        <?php
			if($err){
				echo $errString;	
			} else {
				if(count($property_details)>0){
					echo "<!-- start individual property -->
						<div id='property'>
						<div id='property-title' style='padding-left: 0;'><h1 >".$property_details['title']."</h1></div>
								<div id='property-price'>".(($property_details['displayPrice']==1)?$property_details['price']:"")."</div>
							<div style='clear: both; height: 0;' ></div>
								
								<div id='property-address' >
								<p>".$property_details['address'].", ".$property_details['suburb']." ".$property_details['state']."</p></div>									
								<div id='property-pics'>
									<a href='#' title='".$property_details['title']."'><img src='".((strlen($property_details['featureImage'])>0)?$site_path."dreamcms/app/webroot/uploads/properties/".$property_details['featureImage']:'')."' width='705px' height='400px' border='0'/></a>";
								if(count($property_images['id'])>0){
									for($img=0;$img<4;$img++){
										echo "<a href='#' title='".$property_images['desc'][$img]."'><img src='".$site_path."dreamcms/app/webroot/uploads/properties/".$property_images['thumbs'][$img]."' width='115' height='85' class='thumb' border='0'/></a> ";
									}
								}
								if(count($property_mob_images['id'])>0){
									echo "<div id='mobileGallery'>";
									echo "<!-- Start WOWSlider.com BODY section -->
										  <div id='wowslider-container1'>
											<div class='ws_images'><ul>";
									for($image=0;$image<count($property_mob_images['id']);$image++){
										echo "<li><img src='".$site_path."dreamcms/app/webroot/uploads/properties/".$property_mob_images['files'][$image]."' alt='".$property_mob_images['desc'][$image]."' title='".$property_mob_images['desc'][$image]."' id='wows1_".$image."'/></li>";
									}
									echo    "</ul></div>
											<div class='ws_bullets'><div>
										  </div></div>
										  <!-- Generated by WOWSlider.com v2.4 -->
										  <div class='ws_shadow'></div>
										  </div></div>";
								}
											
					echo		"</div>
								<div id='property-desc'><p>".$property_details['body']."</p></div>
							
							</div></div>
    	<div id='col-right' class='features-panel'>

						
								<div id='prop-details'><div class='beds'> ".$property_details['bedrooms']." </div><div class='baths'> ".$property_details['bathrooms']." </div>".(($property_details['carparks']>0)?"<div class='garage'> ".$property_details['carparks']." </div>":"")."</div>
							<div id='google-map'>".str_replace("<iframe width=\"425\" height=\"350\"","<iframe width=\"290\" height=\"254\"",$property_details['googleMap'])."</div>
							<div id='property-buttons' class='green'>
							<a href='#' onclick='javascript:window.print();'><i class='icon-print'></i> Print Page</a>								
							</div>
								".((strlen($property_details['keyFeatures'])>0)?"<div id='prop-key-features'><h4>Property Features</h4><p>".$property_details['keyFeatures']."</p></div>":"")."
								".((strlen($property_details['inspections'])>0)?"<div id='prop-key-features'><h3>Inspection Times</h3><p style='margin-left:10px'>".str_replace("\n", "<br />", $property_details['inspections'])."</p></div>":"")."
							
							</div>
						             
					<!-- end individual property  -->";
				} else {
					echo $errString;	
				}
			}
		?>      
	</div>

<?php include("inc/foot-brochure-template.php"); ?>